spring:
  config:
    activate:
      on-profile : local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/retrospect
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret:
    key: xQGtzPG4EUTcS5VYdGfxIBwveetugGz2
